CREATE TABLE "de_mi_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "de_mi_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "de_mi_banner" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "de_mi_banner_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256),
	"description" varchar(256),
	"imageUrl" varchar(256),
	"actionLabel" varchar(256),
	"actionUrl" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "de_mi_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "de_mi_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "de_mi_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "de_mi_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoryId" integer NOT NULL,
	"name" varchar(256),
	"description" varchar(256),
	"price" numeric(10, 2) NOT NULL,
	"imageUrl" varchar(256),
	"keywords" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "de_mi_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "de_mi_credentials" (
	"credentialID" "bytea" NOT NULL,
	"userId" text NOT NULL,
	"providerAccountId" text,
	"credentialPublicKey" text NOT NULL,
	"counter" integer NOT NULL,
	"credentialDeviceType" text NOT NULL,
	"credentialBackedUp" boolean NOT NULL,
	"transports" text,
	"authenticatorAttachment" text DEFAULT 'undefined' NOT NULL,
	"browser" text,
	"os" text,
	"platform" text,
	"last_used" bigint,
	"created_at" bigint,
	CONSTRAINT "de_mi_credentials_credentialID_unique" UNIQUE("credentialID")
);
--> statement-breakpoint
CREATE TABLE "de_mi_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"bio" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255),
	"disablePasskey" boolean
);
--> statement-breakpoint
CREATE TABLE "de_mi_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "de_mi_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "de_mi_account" ADD CONSTRAINT "de_mi_account_userId_de_mi_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."de_mi_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "de_mi_category" ADD CONSTRAINT "de_mi_category_createdById_de_mi_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."de_mi_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "de_mi_product" ADD CONSTRAINT "de_mi_product_categoryId_de_mi_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."de_mi_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "de_mi_product" ADD CONSTRAINT "de_mi_product_createdById_de_mi_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."de_mi_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "de_mi_session" ADD CONSTRAINT "de_mi_session_userId_de_mi_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."de_mi_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "de_mi_credentials" ADD CONSTRAINT "de_mi_credentials_userId_de_mi_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."de_mi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "de_mi_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "banner_title_idx" ON "de_mi_banner" USING btree ("title");--> statement-breakpoint
CREATE INDEX "category_created_by_idx" ON "de_mi_category" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "category_name_idx" ON "de_mi_category" USING btree ("name");--> statement-breakpoint
CREATE INDEX "product_created_by_idx" ON "de_mi_product" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "product_name_idx" ON "de_mi_product" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "de_mi_session" USING btree ("userId");