CREATE TABLE "de_mi_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "de_mi_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(100) NOT NULL,
	"description" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "de_mi_role_permission" (
	"roleId" integer NOT NULL,
	"permissionId" integer NOT NULL,
	CONSTRAINT "de_mi_role_permission_roleId_permissionId_pk" PRIMARY KEY("roleId","permissionId")
);
--> statement-breakpoint
CREATE TABLE "de_mi_role" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "de_mi_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" varchar(255),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "de_mi_product" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "de_mi_user" ADD COLUMN "roleId" integer;--> statement-breakpoint
ALTER TABLE "de_mi_role_permission" ADD CONSTRAINT "de_mi_role_permission_roleId_de_mi_role_id_fk" FOREIGN KEY ("roleId") REFERENCES "public"."de_mi_role"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "de_mi_role_permission" ADD CONSTRAINT "de_mi_role_permission_permissionId_de_mi_permission_id_fk" FOREIGN KEY ("permissionId") REFERENCES "public"."de_mi_permission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "permission_key_idx" ON "de_mi_permission" USING btree ("key");--> statement-breakpoint
CREATE INDEX "role_permission_permission_idx" ON "de_mi_role_permission" USING btree ("permissionId");--> statement-breakpoint
CREATE UNIQUE INDEX "role_name_idx" ON "de_mi_role" USING btree ("name");--> statement-breakpoint
ALTER TABLE "de_mi_user" ADD CONSTRAINT "de_mi_user_roleId_de_mi_role_id_fk" FOREIGN KEY ("roleId") REFERENCES "public"."de_mi_role"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "de_mi_role" ("name", "description", "createdAt") VALUES
	('admin', 'Full access to application resources', NOW()),
	('editor', 'Manage application content', NOW()),
	('user', 'Read application content', NOW())
ON CONFLICT ("name") DO NOTHING;
--> statement-breakpoint
UPDATE "de_mi_user"
SET "roleId" = role."id"
FROM "de_mi_role" role
WHERE role."name" = 'user' AND "de_mi_user"."roleId" IS NULL;
--> statement-breakpoint
INSERT INTO "de_mi_permission" ("key", "description") VALUES
	('admin.products', 'Read products'),
	('admin.products:edit', 'Edit products'),
	('admin.products:manage', 'Manage products'),
	('admin.categories', 'Read categories'),
	('admin.categories:edit', 'Edit categories'),
	('admin.categories:manage', 'Manage categories'),
	('admin.banners', 'Read banners'),
	('admin.banners:edit', 'Edit banners'),
	('admin.banners:manage', 'Manage banners'),
	('admin.users', 'Read users'),
	('admin.users:edit', 'Edit users'),
	('admin.users:manage', 'Manage users')
ON CONFLICT ("key") DO NOTHING;
--> statement-breakpoint
INSERT INTO "de_mi_role_permission" ("roleId", "permissionId")
SELECT role."id", permission."id"
FROM "de_mi_role" role
JOIN "de_mi_permission" permission ON permission."key" IN (
	'admin.products:edit',
	'admin.products:manage',
	'admin.categories:edit',
	'admin.categories:manage',
	'admin.banners:edit',
	'admin.banners:manage',
	'admin.users:edit',
	'admin.users:manage'
)
WHERE role."name" = 'admin'
ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "de_mi_role_permission" ("roleId", "permissionId")
SELECT role."id", permission."id"
FROM "de_mi_role" role
JOIN "de_mi_permission" permission ON permission."key" IN (
	'admin.products:edit',
	'admin.categories:edit',
	'admin.banners:edit'
)
WHERE role."name" = 'editor'
ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "de_mi_role_permission" ("roleId", "permissionId")
SELECT role."id", permission."id"
FROM "de_mi_role" role
JOIN "de_mi_permission" permission ON permission."key" IN (
	'admin.products',
	'admin.categories'
)
WHERE role."name" = 'user'
ON CONFLICT DO NOTHING;